#!/bin/sh

USER=mengbo

cp -f /etc/defaults/etc/skel/.bashrc ~
cat >> ~/.bashrc << EOF

#Set PATH so it includes user's private bin if it exists
if [ -d "\${HOME}/bin" ] ; then
  PATH=\${HOME}/bin:\${PATH}
fi

# Use a vi-style command line editing interface
set -o vi

# Set the locale
export LANG=zh_CN.UTF-8
EOF

cp -f /etc/defaults/etc/skel/.inputrc ~
cat >> ~/.inputrc << EOF

# Allow 8-bit input/output
set meta-flag on
set convert-meta off
set input-meta on
set output-meta on
EOF

mkdir -p ~/bin

cat >> ~/.bashrc << EOF

# Set the character encoding used inside GVim
alias gvim="gvim.bat --cmd 'set encoding=utf-8'"
EOF
#ln -f "/cygdrive/c/Users/$USER/_vimrc" ~/.vimrc
#ln -f "/cygdrive/c/Users/$USER/_gvimrc" ~/.gvimrc
#ln -f ~/_viminfo ~/.viminfo

ln -fs "/cygdrive/c/Program Files/PuTTY/plink.exe" ~/bin/plink
