#!/bin/sh -v

brew install ntfs-3g

if [ ! -f /sbin/mount_ntfs.orig ]; then
	sudo mv /sbin/mount_ntfs /sbin/mount_ntfs.orig
fi
sudo ln -sf /usr/local/sbin/mount_ntfs /sbin/mount_ntfs

sudo cp -rfX /usr/local/Cellar/fuse4x-kext/0.9.2/Library/Extensions/fuse4x.kext /Library/Extensions
sudo chmod +s /Library/Extensions/fuse4x.kext/Support/load_fuse4x
#sudo kextunload -b org.fuse4x.kext.fuse4x
