#!/bin/sh -v

brew install ntfs-3g

if [ ! -f /sbin/mount_ntfs.orig ]; then
	sudo mv /sbin/mount_ntfs /sbin/mount_ntfs.orig
fi
sudo ln -sf /usr/local/sbin/mount_ntfs /sbin/mount_ntfs

sudo /bin/cp -RfX /usr/local/Cellar/osxfuse/2.6.2/Library/Filesystems/osxfusefs.fs /Library/Filesystems
sudo chmod +s /Library/Filesystems/osxfusefs.fs/Support/load_osxfusefs
#sudo kextunload -b com.github.osxfuse.filesystems.osxfusefs
