#!/bin/sh -v

brew install dsocks
if [ ! -f /usr/local/bin/dsocks.sh.default ]; then
        mv /usr/local/bin/dsocks.sh /usr/local/bin/dsocks.sh.default
fi
cat > /usr/local/bin/dsocks.sh << EOF
#!/bin/sh

export DSOCKS_VERSION=5
export DSOCKS_PROXY="127.0.0.1:7070"

export DSOCKS_NAMESERVER="4.2.2.2"

if [ \`uname -s\` = "Darwin" ]; then
  # for MacOS X...
  LIBDSOCKS=/usr/local/lib/libdsocks.dylib
  DYLD_INSERT_LIBRARIES=\$LIBDSOCKS DYLD_FORCE_FLAT_NAMESPACE=1 exec "\$@"
else
  LIBDSOCKS=/usr/local/lib/libdsocks.so.1.0
  LD_PRELOAD=\$LIBDSOCKS exec "\$@"
fi
EOF
chmod +x /usr/local/bin/dsocks.sh
