#!/bin/sh -v

brew install tcptraceroute

brew install hping

brew install nmap

#brew install wireshark

brew install minicom lrzsz
if [ ! -f /usr/local/etc/minirc.dfl.default ]; then
        mv /usr/local/etc/minirc.dfl /usr/local/etc/minirc.dfl.default
fi
cat > /usr/local/etc/minirc.9600 << EOF
pu lock /usr/local/Cellar/minicom/2.6.1/var
pu escape-key Escape (Meta)
pu port             /dev/ttyS0
pu baudrate         9600
pu bits             8
pu parity           N
pu stopbits         1
pu minit
pu mreset
pu rtscts           No
EOF
ln -f -s /usr/local/etc/minirc.9600 /usr/local/etc/minirc.dfl
