#!/bin/sh -v

brew install tcptraceroute

brew install hping

brew install nmap

#brew install wireshark

# Please download and install USB to Serial interface bridge driver, download URL is
# http://www.prolific.com.tw/UserFiles/files/md_PL2303_MacOSX10_6_dmg_v1_4_0.zip
brew install minicom lrzsz
cat /usr/local/etc/minirc.dfl > $HOME/.minirc.dfl
cat >> $HOME/.minirc.dfl << EOF
pu port             /dev/tty.usbserial
pu baudrate         9600
pu bits             8
pu parity           N
pu stopbits         1
pu minit
pu mreset
pu rtscts           No
EOF
