#!/bin/sh -v

cat > ~/.irbrc << EOF
IRB.conf[:AUTO_INDENT] = true
require 'irb/completion'
IRB.conf[:SAVE_HISTORY] = 1000
IRB.conf[:HISTORY_FILE] = "#{ENV['HOME']}/.irb-save-history"
IRB.conf[:PROMPT_MODE] = :SIMPLE
EOF
