#!/bin/sh -v

cp /etc/skel/.bashrc $HOME/.bash_interactive

cp $HOME/.bashrc $HOME/.bashrc.orig

cat > $HOME/.bashrc << EOF
# ~/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
# for examples

# If running interactively
if [ -n "\$PS1" ]; then
    . "\$HOME/.bash_interactive"
fi

EOF
