#!/bin/sh -v

cp $HOME/.profile $HOME/.profile.orig

sed '/# if running bash/,+7d' $HOME/.profile.orig > $HOME/.profile
cat >> $HOME/.profile <<EOF

# if running bash
if [ -n "\$BASH_VERSION" ]; then
    # include .bashrc if it exists
    if [ -f "\$HOME/.bashrc" ]; then
	. "\$HOME/.bashrc"
    fi
fi
EOF
