#!/bin/sh -v

git clone https://github.com/sstephenson/rbenv.git ~/.rbenv

mkdir -p "~/.rbenv/plugins"
git clone https://github.com/sstephenson/ruby-build.git ~/.rbenv/plugins/ruby-build
git clone git://github.com/sstephenson/rbenv-gem-rehash.git ~/.rbenv/plugins/rbenv-gem-rehash
git clone https://github.com/rkh/rbenv-update.git ~/.rbenv/plugins/rbenv-update

cat >> $HOME/.bashrc << EOF

# Add ~/.rbenv/bin to your \$PATH
export PATH="\$HOME/.rbenv/bin:\$PATH"
# Add rbenv init to your shell
eval "\$(rbenv init -)"
EOF
