#!/bin/sh -v

[ `which aptitude` ] && sudo aptitude install curl git

#curl -L get.rvm.io | bash -s stable

cat >> $HOME/.bashrc << EOF

# Load RVM into a shell session *as a function*
[[ -s "\$HOME/.rvm/scripts/rvm" ]] && source "\$HOME/.rvm/scripts/rvm"
[[ -r \$rvm_path/scripts/completion ]] && . \$rvm_path/scripts/completion
EOF
