#!/bin/bash -v

source $HOME/.rvm/scripts/rvm

#sudo `rvm requirements | grep -e "^ *ruby: /usr/bin/apt-get install" |sed s/^.*apt-get/aptitude/`

#rvm install 1.8.7
#rvm use 1.8.7@global
#gem install bundler
#rvm gemset create default

#rvm use 1.8.7@default --default

#rvm install 1.9.3
#rvm use 1.9.3@global
#gem install bundler
#rvm gemset create default
