#!/bin/bash

# Please see the ruby-build wiki for solutions to common problems.
# https://github.com/sstephenson/ruby-build/wiki

mkdir -p ~/.rbenv/versions/2.1.0/lib
rbenv install 2.1.0

rbenv install 2.2.3

rbenv global 2.2.3
