#!/bin/bash

run() {
	echo $@
	eval $@
}

source $HOME/.rvm/scripts/rvm

#INST=`rvm requirements | grep -e '^ *ruby: /usr/bin/apt-get install' | sed s/^.*apt-get/aptitude/`
#run sudo $INST

run rvm install 1.8.7
run rvm use 1.8.7 --default

run rvm install 1.9.3
