#!/bin/bash

gem sources \
	--add https://gems.ruby-china.org/ \
	--remove https://rubygems.org/

gem install bundler

bundle config mirror.https://rubygems.org https://gems.ruby-china.org
bundle config path vendor/bundle
