#!/bin/bash

run() {
	echo $@
	eval $@
}

source $HOME/.rvm/scripts/rvm

#run rvm use default

#run sudo aptitude -y install imagemagick
#run sudo aptitude -y install libmagick9-dev
#run gem install rmagick
