#!/bin/bash

run() {
	echo $@
	eval $@
}

source $HOME/.rvm/scripts/rvm

run rvm use 1.9.3
run rvm gemset create rails
run rvm alias create rails 1.9.3@rails
run rvm use rails

[ `which aptitude` ] && run sudo aptitude -y install sqlite3 libsqlite3-dev
run gem install sqlite3

[ `which aptitude` ] && run sudo aptitude -y install mysql-client libmysqlclient-dev
[ `which brew` ] && run brew install mysql
run gem install mysql2

run gem install rails
