#!/bin/bash

run() {
	echo $@
	eval $@
}

source $HOME/.rvm/scripts/rvm

run rvm use 1.9.3
run rvm gemset create rails
run rvm alias create rails 1.9.3@rails
run rvm use rails

run sudo aptitude -y install sqlite3
run sudo aptitude -y install libsqlite3-dev
run gem install sqlite3

run sudo aptitude -y install mysql-client
run sudo aptitude -y install libmysqlclient-dev
run gem install mysql2

run gem install rails
run gem install termios
run gem install capistrano
