#!/bin/bash

run() {
	echo $@
	eval $@
}

source $HOME/.rvm/scripts/rvm

run rvm use 1.9.3
run rvm gemset create jekyll
run rvm alias create jekyll 1.9.3@jekyll
run rvm use jekyll

[ `which aptitude` ] && run sudo aptitude -y install python-pygments
[ `which brew` ] && run sudo easy_install Pygments
run gem install jekyll
run gem install rdiscount
