#!/bin/bash

run() {
	echo $@
	eval $@
}

source $HOME/.rvm/scripts/rvm

#run rvm get stable

source $HOME/.rvm/scripts/rvm

#run rvm upgrade 1.8.7-p307 1.8.7
#run rvm use 1.8.7@global
#run gem update
#run rvm use default
#run gem update
#run rvm remove 1.8.7-p307

#run rvm install 1.9.3
#
#run rvm gemset copy 1.9.3-p194 1.9.3
#run rvm use 1.9.3
#run gem update
#
#run rvm gemset copy rails 1.9.3@rails
#run rvm alias create rails 1.9.3@rails
#run rvm use rails
#run gem update
#
#run rvm remove ruby-1.9.3-p194

#run rvm cleanup all
