#!/bin/bash

run() {
	echo $@
	eval $@
}

source $HOME/.rvm/scripts/rvm

run rvm -v
run rvm get stable

source $HOME/.rvm/scripts/rvm

#run rvm list
#run rvm all do gem -v
#run rvm alias list
#run rvm upgrade 1.8.7-p307 1.8.7
#run rvm upgrade 1.9.3-p194 1.9.3
#run rvm list
#run rvm all do gem -v
#run rvm alias list
