#!/bin/sh -v

#/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

mkdir -p ~/.profile.d
cat > ~/.profile.d/homebrew.sh << 'EOF'
eval "$(/opt/homebrew/bin/brew shellenv)"

#BOTTLE_DOMAIN=https://mirrors.ustc.edu.cn/homebrew-bottles
BOTTLE_DOMAIN=https://mirrors.tuna.tsinghua.edu.cn/homebrew-bottles
export HOMEBREW_BOTTLE_DOMAIN=$BOTTLE_DOMAIN
export HOMEBREW_NO_AUTO_UPDATE=1
EOF
