#!/bin/sh -v

#brew install zsh
#grep -q /usr/local/bin/zsh /etc/shells || \
#	sudo sh -c  "echo /usr/local/bin/zsh >> /etc/shells" 
#chsh -s /usr/local/bin/zsh

mkdir -p ~/.profile.d
cat > ~/.zprofile << 'EOF'
export PATH=$HOME/bin:$PATH

if [ -d ~/.profile.d ]; then
    for i in ~/.profile.d/*.sh; do
        if [ -r $i ]; then
            source $i
        fi
    done
    unset i
fi
EOF

mkdir -p ~/.zshrc.d
cat > ~/.zshrc << 'EOF'
# https://docs.brew.sh/Shell-Completion
FPATH="$(brew --prefix)/share/zsh/site-functions:${FPATH}"

if [ -d ~/.zshrc.d ]; then
    for i in ~/.zshrc.d/*.zsh; do
        if [ -r $i ]; then
            source $i
        fi
    done
    unset i
fi
EOF
