#!/bin/sh -v

brew install fd ripgrep tree
brew install fzf

cat > ~/.profile.d/30fzf.sh << 'EOF'
export RUNEWIDTH_EASTASIAN=0
export FZF_DEFAULT_COMMAND='fd --type f'
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
export FZF_DEFAULT_OPTS="--inline-info"
export FZF_CTRL_T_OPTS="--inline-info --preview='fzf-previewer {}'"

# Scheme name: selenized-dark
# Scheme system: base16
# Scheme author: Jan Warchol (https://github.com/jan-warchol/selenized) / adapted to base16 by ali
# Template author: Tinted Theming (https://github.com/tinted-theming)

export FZF_DEFAULT_OPTS="$FZF_DEFAULT_OPTS"\
" --color=bg+:#184956,bg:#103c48,spinner:#41c7b9,hl:#4695f7"\
" --color=fg:#72898f,header:#4695f7,info:#dbb32d,pointer:#41c7b9"\
" --color=marker:#41c7b9,fg+:#cad8d9,prompt:#dbb32d,hl+:#4695f7"
EOF

mkdir -p ~/bin
cat > ~/bin/fzf-previewer << 'EOF'
#!/bin/sh

FT=$(file -b "$1") || "$1"

case "${FT}" in
    *"text"*)
        head -100 "$1"
        ;;
    "directory")
        tree -L 1 --noreport -C "$1"
        ;;
    *"No such file or directory"*)
        echo "$1"
        ;;
    *)
        echo "$FT"
esac
EOF
chmod +x ~/bin/fzf-previewer
