#!/bin/sh -v

brew tap homebrew/cask-fonts
brew install font-meslo-lg-nerd-font

brew install lsd
mkdir -p ~/.zshrc.d
cat > ~/.zshrc.d/90lsd.zsh << 'EOF'
lsd -d . &>/dev/null && alias ls='lsd'
EOF

brew install coreutils
mkdir -p ~/.profile.d
curl -fsSL -o ~/.dir_colors \
    https://raw.githubusercontent.com/seebi/dircolors-solarized/master/dircolors.256dark
cat > ~/.profile.d/30dircolors.sh << 'EOF'
eval `gdircolors ~/.dir_colors`
# fix dircolors for Selenized
export LS_COLORS="$LS_COLORS:ow=1;7;34:st=30;44:su=30;41"
EOF

#brew install vivid
#mkdir -p ~/.profile.d
#cat > ~/.profile.d/30vivid.sh << EOF
#export LS_COLORS="$(vivid generate solarized-dark)"
#EOF
