#!/bin/sh -v

brew tap homebrew/cask-fonts
brew cask install font-meslo-lg-nerd-font

brew install lsd

cat > ~/.profile.d/lsd.sh << EOF
alias ls='lsd'
EOF

brew install coreutils

mkdir -p ~/.profile.d
wget -O ~/.dir_colors \
    https://raw.githubusercontent.com/seebi/dircolors-solarized/master/dircolors.256dark
cat > ~/.profile.d/dircolors.sh << EOF
eval \`gdircolors ~/.dir_colors\`
EOF

