#!/bin/sh -v

brew install aichat

GHPROXY="https://gh-proxy.com/"
INTE_ZSH="https://raw.githubusercontent.com/sigoden/aichat/main/scripts/shell-integration/integration.zsh"
curl -s -L "${GHPROXY}${INTE_ZSH}" | sed 's#\\ee#^Y#' > ~/.zshrc.d/90aichat.zsh

# Link the config file path
mkdir -p "$HOME/Library/Application Support/aichat" 
ln -sf "$HOME/Library/Application Support/aichat" ~/.config/aichat

# RAC required tools
brew install poppler
brew install pandoc
npm config set prefix '~/.local/'
npm install -g rag-crawler

# Custom theme
CONF_DIR="${HOME}/.config/aichat"
GHPROXY="https://gh-proxy.com/"
DARK="https://raw.githubusercontent.com/Okeanos/selenized/sublime-textmate/editors/sublime-WIP/Selenized%20Dark.tmTheme"
LIGHT="https://raw.githubusercontent.com/Okeanos/selenized/sublime-textmate/editors/sublime-WIP/Selenized%20Light.tmTheme"
curl -L -o "${CONF_DIR}/dark.tmTheme" "${GHPROXY}${DARK}"
curl -L -o "${CONF_DIR}/light.tmTheme" "${GHPROXY}${LIGHT}"
