#!/bin/sh -v

brew install aichat

GHPROXY="https://gh-proxy.com/"
INTE_ZSH="https://raw.githubusercontent.com/sigoden/aichat/main/scripts/shell-integration/integration.zsh"
curl -s -L "${GHPROXY}${INTE_ZSH}" | sed 's#\\ee#^Y#' > ~/.zshrc.d/90aichat.zsh

# RAC required tools
#brew install poppler
#brew install pandoc
#npm config set prefix '~/.local/'
#npm install -g rag-crawler
