#!/bin/sh -v

brew install minicom lrzsz
cat /usr/local/etc/minirc.dfl > $HOME/.minirc.dfl
cat >> $HOME/.minirc.dfl << EOF
#pu port             /dev/tty.usbserial
pu port             /dev/tty.OSTRAN
pu baudrate         9600
pu bits             8
pu parity           N
pu stopbits         1
pu minit
pu mreset
pu rtscts           No
EOF
