#!/bin/sh -v

# nmap nping ncat
brew install nmap
chmod go-w /opt/homebrew/Cellar

brew install masscan

brew install zmap

brew install socat

brew install mitmproxy

brew install sqlmap

brew install hashcat

brew install proxychains-ng

brew install ansible

brew install govc
