#!/bin/sh -v

brew install tcptraceroute

brew install hping

brew install nmap
ln -s /usr/local/lib/python2.7/site-packages/ndiff.py ~/bin/ndiff

brew install masscan

brew install zmap

brew install socat

brew install mitmproxy

brew install sqlmap

brew install hashcat

brew install proxychains-ng

brew install ansible
