#!/bin/sh -v

brew install tcptraceroute

brew install hping

brew install nmap

brew install zmap

brew install mitmproxy

brew install sqlmap

brew install hashcat

brew install proxychains-ng
cp /usr/local/etc/proxychains.conf /usr/local/etc/proxychains.conf.default
sed 's/^socks4.*9050/socks5 127.0.0.1 7070/' \
	/usr/local/etc/proxychains.conf.default \
	> /usr/local/etc/proxychains.conf
