#!/bin/sh -v

brew install rustup

cat > ~/.zshrc.d/20rust.zsh << 'EOF'
export PATH="/opt/homebrew/opt/rustup/bin:$HOME/.cargo/bin:$PATH"
EOF

cat > ~/.cargo/config.toml << 'EOF'
[source.crates-io]
replace-with = 'ustc'

[registries.ustc]
index = "sparse+https://mirrors.ustc.edu.cn/crates.io-index/"
EOF
