#!/bin/sh -v

brew install ruby

cat > ~/.profile.d/ruby.sh << EOF
RUBYDIR=\$(brew --prefix ruby)
export PATH="\$RUBYDIR/bin:\$PATH"
GEMDIR=\$(gem environment gemdir)
export PATH="\$GEMDIR/bin:\$PATH"
EOF
