#!/bin/sh -v

brew install alacritty

cat > ~/.alacritty.toml << 'EOF'
[env]
LC_ALL = "zh_CN.UTF-8"
TERM = "alacritty"

[window]
opacity = 1.0

[window.dimensions]
columns = 80
lines = 24

[window.padding]
x = 5
y = 5

[scrolling]
history = 10000

# Font configuration
[font]
size = 16.0

[font.normal]
family = "MesloLGS Nerd Font"
style = "Regular"

[font.bold]
family = "MesloLGS Nerd Font"
style = "Bold"

[font.italic]
family = "MesloLGS Nerd Font"
style = "Italic"

[font.bold_italic]
family = "MesloLGS Nerd Font"
style = "Bold Italic"


# Colors (Solarized Dark)
# Default colors
[colors.primary]
background = '#002b36'
foreground = '#839496'

# Normal colors
[colors.normal]
black   = '#073642'
red     = '#dc322f'
green   = '#859900'
yellow  = '#b58900'
blue    = '#268bd2'
magenta = '#d33682'
cyan    = '#2aa198'
white   = '#eee8d5'

# Bright colors
[colors.bright]
black   = '#002b36'
red     = '#cb4b16'
green   = '#586e75'
yellow  = '#657b83'
blue    = '#839496'
magenta = '#6c71c4'
cyan    = '#93a1a1'
white   = '#fdf6e3'

[bell.command]
# macOS
program = "osascript"
args = ["-e", "beep"]
# Linux
#program = "xkbbell"

[selection]
save_to_clipboard = true

[[keyboard.bindings]]
key = "N"
mods = "Command"
action = "CreateNewWindow"

[[keyboard.bindings]]
key = "Space"
mods = "Control"
chars = "\u0000"
EOF

# Don't forget install Pictogram, and change icon.
# Don't forget install HazeOver.
