#!/bin/sh -v

brew install ghostty
brew install viu

mkdir -p ~/.config/ghostty/themes

cat > ~/.config/ghostty/config << 'EOF'
font-family = MesloLGS Nerd Font
# macOS
font-size = 16
# Linux
#font-size = 12

window-theme = light
macos-titlebar-style = native

theme = Selenized Dark

window-width = 80
# macOS
window-height = 24
# Linux
#window-height = 27

mouse-hide-while-typing = true
mouse-scroll-multiplier = 2
EOF

cat > ~/.config/ghostty/themes/Selenized\ Dark << 'EOF'
palette = 0=#184956
palette = 1=#fa5750
palette = 2=#75b938
palette = 3=#dbb32d
palette = 4=#4695f7
palette = 5=#f275be
palette = 6=#41c7b9
palette = 7=#72898f
palette = 8=#2d5b69
palette = 9=#ff665c
palette = 10=#84c747
palette = 11=#ebc13d
palette = 12=#58a3ff
palette = 13=#ff84cd
palette = 14=#53d6c7
palette = 15=#cad8d9
background = 103c48
foreground = adbcbc
cursor-color = adbcbc
selection-background = 184956
selection-foreground = 53d6c7
EOF
