#!/bin/sh -v

brew install lua python
brew cask install macvim

brew tap homebrew/cask-fonts
brew cask install font-meslo-lg-nerd-font

brew install the_silver_searcher

mkdir -p ~/bin
ln -sf /Applications/MacVim.app/Contents/bin/view ~/bin/view
ln -sf /Applications/MacVim.app/Contents/bin/vim ~/bin/vi
ln -sf /Applications/MacVim.app/Contents/bin/vim ~/bin/vim
ln -sf /Applications/MacVim.app/Contents/bin/vimdiff ~/bin/vimdiff
