#!/bin/sh -v

brew tap homebrew/cask-fonts
brew cask install font-menlo-for-powerline
brew install editorconfig
brew cask install macvim

mkdir -p ~/bin
ln -sf /Applications/MacVim.app/Contents/bin/view ~/bin/view
ln -sf /Applications/MacVim.app/Contents/bin/vim ~/bin/vi
ln -sf /Applications/MacVim.app/Contents/bin/vim ~/bin/vim
ln -sf /Applications/MacVim.app/Contents/bin/vimdiff ~/bin/vimdiff
