#!/bin/sh -v

# These devices appear to be supported by Apple's generic IOUSBSerial driver.

#brew install pl2303

# https://forum.arduino.cc/index.php?topic=427825.0
#brew install ftdi-vcp-driver

# https://github.com/mengbo/ch340g-ch34g-ch34x-mac-os-x-driver
#brew tap mengbo/ch340g-ch34g-ch34x-mac-os-x-driver \
#	https://github.com/mengbo/ch340g-ch34g-ch34x-mac-os-x-driver
#brew install wch-ch34x-usb-serial-driver
