#!/bin/sh -v

brew cask install pl2303

# https://forum.arduino.cc/index.php?topic=427825.0
#brew cask install ftdi-vcp-driver

# https://github.com/mengbo/ch340g-ch34g-ch34x-mac-os-x-driver
#brew tap mengbo/ch340g-ch34g-ch34x-mac-os-x-driver \
#	https://github.com/mengbo/ch340g-ch34g-ch34x-mac-os-x-driver
brew cask install wch-ch34x-usb-serial-driver
