#!/bin/sh -v

MIRROR=http://mirrors.ustc.edu.cn/ubuntu

if [ ! -f /etc/apt/sources.list.default ]; then
	sudo cp /etc/apt/sources.list /etc/apt/sources.list.default
fi
sudo cp /etc/apt/sources.list /etc/apt/sources.list.orig
sudo tee /etc/apt/sources.list << EOF > /dev/null
deb ${MIRROR} $(lsb_release -cs) main multiverse restricted universe
# deb-src ${MIRROR} $(lsb_release -cs) main multiverse restricted universe
deb ${MIRROR} $(lsb_release -cs)-updates main multiverse restricted universe
# deb-src ${MIRROR} $(lsb_release -cs)-updates main multiverse restricted universe
deb ${MIRROR} $(lsb_release -cs)-backports main multiverse restricted universe
# deb-src ${MIRROR} $(lsb_release -cs)-backports main multiverse restricted universe
deb http://security.ubuntu.com/ubuntu $(lsb_release -cs)-security main multiverse restricted universe
# deb-src http://security.ubuntu.com/ubuntu $(lsb_release -cs)-security main multiverse restricted universe
# deb ${MIRROR} $(lsb_release -cs)-proposed main multiverse restricted universe
# deb-src ${MIRROR} $(lsb_release -cs)-proposed main multiverse restricted universe
# deb http://archive.canonical.com/ubuntu $(lsb_release -cs) partner
EOF
# echo 'Acquire::ForceIPv4 "true";' | sudo tee /etc/apt/apt.conf.d/99force-ipv4
sudo apt update
sudo apt upgrade
sudo apt full-upgrade
