#!/bin/sh -v

MIRROR=http://mirrors.ustc.edu.cn/ubuntu

if [ ! -f /etc/apt/sources.list.default ]; then
	cp /etc/apt/sources.list /etc/apt/sources.list.default
fi
cp /etc/apt/sources.list /etc/apt/sources.list.orig
cat > /etc/apt/sources.list << EOF
deb ${MIRROR} $(lsb_release -cs) main multiverse restricted universe
# deb-src ${MIRROR} $(lsb_release -cs) main multiverse restricted universe
deb ${MIRROR} $(lsb_release -cs)-updates main multiverse restricted universe
# deb-src ${MIRROR} $(lsb_release -cs)-updates main multiverse restricted universe
deb ${MIRROR} $(lsb_release -cs)-backports main multiverse restricted universe
# deb-src ${MIRROR} $(lsb_release -cs)-backports main multiverse restricted universe
deb http://security.ubuntu.com/ubuntu $(lsb_release -cs)-security main multiverse restricted universe
# deb-src http://security.ubuntu.com/ubuntu $(lsb_release -cs)-security main multiverse restricted universe
# deb ${MIRROR} $(lsb_release -cs)-proposed main multiverse restricted universe
# deb-src ${MIRROR} $(lsb_release -cs)-proposed main multiverse restricted universe
# deb http://archive.canonical.com/ubuntu $(lsb_release -cs) partner
EOF
apt update
apt upgrade
apt full-upgrade
