#!/bin/sh -v

# For the bug in one of the ebtables support script.
# sudo cp -p /bin/true /sbin/ebtables

umask 0022
mkdir -p ~/.profile.d
cat > ~/.profile.d/wsl.sh << EOF
#Fix mkdir command has wrong permissions
if grep -q Microsoft /proc/version; then
    if [[ "\$(umask)" == '000' ]]; then
	umask 0022
    fi
    export DISPLAY=:0.0

    # https://github.com/rupor-github/ssh-agent-wsl
    eval "\$(ssh-agent-wsl -r -H /mnt/c/Windows/System32/pipe-connector.exe)" > /dev/null
fi
EOF


echo "Restart your shell so that umask changes take effect."
