#!/bin/sh -v

sudo tee /etc/apt/sources.list.d/google-chrome.list << EOF > /dev/null
deb [arch=amd64] https://repo.fdzh.org/chrome/deb/ stable main
EOF
wget -q https://repo.fdzh.org/chrome/linux_signing_key.pub -O- | sudo apt-key add -
sudo apt update
sudo apt install google-chrome-stable
