#!/bin/sh -v

sudo apt-get install -y --no-install-recommends \
	apt-transport-https ca-certificates curl software-properties-common

curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -

echo "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" \
	| sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

sudo apt-get remove docker docker-engine
sudo apt-get update
sudo apt-get -y install docker-ce


# Add the docker group if it doesn't already exist.
sudo groupadd docker

# Add the connected user "${USER}" to the docker group.
# Change the user name to match your preferred user.
# You may have to logout and log back in again for
# this to take effect.
sudo gpasswd -a ${USER} docker

sudo systemctl enable docker


sudo tee /etc/docker/daemon.json << EOF > /dev/null
{
  "dns": ["202.118.48.1", "202.118.48.252"]
}
EOF
sudo systemctl restart docker


sudo docker pull busybox
sudo docker run -i -t busybox /bin/echo "hello, docker."
