#!/bin/sh -v

cat > /etc/apt/sources.list.d/dropbox.list << EOF
deb https://linux.dropbox.com/ubuntu $(lsb_release -cs) conntrib
EOF
apt-key adv --keyserver pgp.mit.edu \
	--recv-keys 1C61A2656FB57B7E4DE0F4C1FC918B335044912E
apt update
apt install dropbox
