#!/bin/sh -v

sudo tee /etc/apt/sources.list.d/dropbox.list << EOF > /dev/null
deb https://linux.dropbox.com/ubuntu $(lsb_release -cs) conntrib
EOF
sudo apt-key adv --keyserver pgp.mit.edu \
	--recv-keys 1C61A2656FB57B7E4DE0F4C1FC918B335044912E
sudo apt update
sudo apt install dropbox
