#!/bin/sh -v

sudo tee /etc/apt/sources.list.d/resilio-sync.list << EOF > /dev/null
deb http://linux-packages.resilio.com/resilio-sync/deb resilio-sync non-free
EOF
wget -qO - https://linux-packages.resilio.com/resilio-sync/key.asc \
	| sudo apt-key add -
sudo apt update
sudo apt install resilio-sync
sudo sed -i s/WantedBy=multi-user.target/WantedBy=default.target/ \
	/usr/lib/systemd/user/resilio-sync.service
systemctl --user enable resilio-sync
systemctl --user start  resilio-sync
sudo loginctl enable-linger "${USER}"
