#!/bin/sh -v

sudo tee /etc/apt/sources.list.d/virtualbox.list << EOF > /dev/null
deb http://download.virtualbox.org/virtualbox/debian xenial contrib
EOF
wget -q https://www.virtualbox.org/download/oracle_vbox_2016.asc -O- \
	| sudo apt-key add -
wget -q https://www.virtualbox.org/download/oracle_vbox.asc -O- \
	| sudo apt-key add -
sudo apt update
sudo apt install virtualbox-5.1

sudo usermod -G vboxusers -a ${USER}
