#!/bin/sh -v

cat > /etc/apt/sources.list.d/resilio-sync.list << EOF
deb http://linux-packages.resilio.com/resilio-sync/deb resilio-sync non-free
EOF
wget -qO - https://linux-packages.resilio.com/resilio-sync/key.asc | sudo apt-key add -
aptitude -y update
aptitude -y install resilio-sync
