#!/usr/bin/env bash

for java_dir in /usr/lib/jvm/*; do
	jenv add "$java_dir"
done

if [ -x /usr/libexec/java_home ]; then
	jenv add "$(/usr/libexec/java_home -v 11.0)"
	jenv add "$(/usr/libexec/java_home -v 1.8)"
fi

jenv global 11.0
