#!/bin/sh -v

brew install mysql

unset TMPDIR
mysql_install_db --verbose --user=`whoami` \
	--basedir="$(brew --prefix mysql)" \
	--datadir=/usr/local/var/mysql \
	--tmpdir=/tmp

mysql.server start
mysql_secure_installation
