#!/bin/sh

git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch v0.9.0


mkdir -p ~/.bashrc.d
cat > ~/.bashrc.d/asdf.bash << 'EOF'
. $HOME/.asdf/asdf.sh
. $HOME/.asdf/completions/asdf.bash
EOF


echo "Restart your shell so that PATH changes take effect."
