#!/bin/sh -v

sudo apt install zsh
chsh -s /usr/bin/zsh

sudo apt install tldr

sudo apt install sysstat

sudo apt install screen
cat > ~/.screenrc << EOF
startup_message off
defscrollback 10240
termcapinfo xterm*|xterms*|xs*|rxvt* ti@:te@
EOF

sudo apt install rsync

sudo apt install convmv

sudo apt install tofrodos

sudo apt install unrar

sudo apt install p7zip

sudo apt install curl
sudo apt install libcurl4-gnutls-dev

sudo apt install wget

sudo apt install aria2

sudo apt install lftp
mkdir -p ~/.lftp
cat > ~/.lftp/rc << EOF
set ftp:charset "GB18030"
EOF

sudo apt install vpnc
