#!/bin/sh -v

mkdir -p ~/.profile.d
GHPROXY="https://gh-proxy.com/"
curl -s -L -o ~/.dir_colors \
	"${GHPROXY}https://raw.githubusercontent.com/seebi/dircolors-solarized/master/dircolors.256dark"

cat > ~/.profile.d/dircolors.sh << EOF
eval \`dircolors ~/.dir_colors\`
# fix dircolors for Selenized
export LS_COLORS="$LS_COLORS:ow=1;7;34:st=30;44:su=30;41"
EOF

