#!/bin/sh -v

sudo apt install fzf
sudo ln -sf /usr/share/doc/fzf/examples/completion.zsh \
	/usr/share/zsh/vendor-completions/_fzf

sudo apt install fd-find ripgrep

cat > ~/.profile.d/fzf.sh << EOF
export PATH=/usr/lib/cargo/bin/:\$PATH
export FZF_DEFAULT_COMMAND='fd --type f'
export FZF_CTRL_T_COMMAND="\$FZF_DEFAULT_COMMAND"
export FZF_DEFAULT_OPTS="--inline-info"
export FZF_CTRL_T_OPTS="--inline-info --preview='fzf-previewer {}'"
EOF

cat > ~/bin/fzf-previewer << EOF
#!/bin/sh

FT=\$(file -b "\$1") || "\$1"

case "\${FT}" in
    *"text"*)
        head -100 "\$1"
        ;;
    *"No such file or directory"*)
        echo "\$1"
        ;;
    *)
        echo "\$FT"
esac
EOF
chmod +x ~/bin/fzf-previewer
