#!/bin/sh -v

# For the bug in one of the ebtables support script.
# sudo cp -p /bin/true /sbin/ebtables

umask 0022
mkdir -p ~/.profile.d
cat > ~/.profile.d/wsl.sh << EOF
#Fix mkdir command has wrong permissions
if grep -q Microsoft /proc/version; then
    umask 0022
    export DISPLAY=localhost:0.0
    export DOCKER_HOST=tcp://127.0.0.1:2375

    # https://github.com/rupor-github/ssh-agent-wsl
    eval "\$(ssh-agent-wsl -r -H /mnt/c/Windows/System32/pipe-connector.exe)" > /dev/null
fi
EOF


echo "Restart your shell so that umask changes take effect."
