#!/bin/sh -v

sudo apt install alacritty

mkdir -p ~/.config/alacritty
cat > ~/.config/alacritty/alacritty.toml << 'EOF'
[env]
LC_ALL = "zh_CN.UTF-8"
TERM = "alacritty"

[window]
opacity = 1.0

[window.dimensions]
columns = 80
lines = 24

[window.padding]
x = 5
y = 5

[scrolling]
history = 10000

# Font configuration
[font]
size = 12.0

[font.normal]
family = "MesloLGS Nerd Font"
style = "Regular"

[font.bold]
family = "MesloLGS Nerd Font"
style = "Bold"

[font.italic]
family = "MesloLGS Nerd Font"
style = "Italic"

[font.bold_italic]
family = "MesloLGS Nerd Font"
style = "Bold Italic"

# Colors (Selenized Dark)
# Default colors
[colors.primary]
background = '#103c48'
foreground = '#adbcbc'

# Normal colors
[colors.normal]
black   = '#184956'
red     = '#fa5750'
green   = '#75b938'
yellow  = '#dbb32d'
blue    = '#4695f7'
magenta = '#f275be'
cyan    = '#41c7b9'
white   = '#72898f'

# Bright colors
[colors.bright]
black   = '#2d5b69'
red     = '#ff665c'
green   = '#84c747'
yellow  = '#ebc13d'
blue    = '#58a3ff'
magenta = '#ff84cd'
cyan    = '#53d6c7'
white   = '#cad8d9'

[bell.command]
# macOS
#program = "osascript"
#args = ["-e", "beep"]
# Linux
program = "xkbbell"

[selection]
save_to_clipboard = true

[[keyboard.bindings]]
key = "N"
mods = "Command"
action = "CreateNewWindow"

[[keyboard.bindings]]
key = "Space"
mods = "Control"
chars = "\u0000"
EOF
