#!/bin/sh -v

sudo apt install gnome-backgrounds

sudo apt install gnome-browser-connector gnome-shell-extension-prefs
#gnome-shell-extension-prefs
# Install extensions: appindicator-support & vitals

sudo apt install gnome-tweaks
#gnome-tweaks

# Disable GDM auto-suspend
# https://wiki.archlinux.org/index.php/GDM#GDM_auto-suspend_.28GNOME_3.28.29
#sudo -u Debian-gdm dbus-launch gsettings set \
#	org.gnome.settings-daemon.plugins.power \
#	sleep-inactive-ac-type 'nothing'
