#!/bin/sh -v

GHPROXY="https://gh-proxy.com/"

TAR_URL="https://github.com/sigoden/aichat/releases/download/v0.19.0/aichat-v0.19.0-x86_64-unknown-linux-musl.tar.gz"
curl -s -L "${GHPROXY}${TAR_URL}" | tar zxv -C ~/bin

COMP_ZSH="https://raw.githubusercontent.com/sigoden/aichat/main/scripts/completions/aichat.zsh"
curl -s -L -o ~/.local/share/zsh/site-functions/_aichat "${GHPROXY}${COMP_ZSH}"

INTE_ZSH="https://raw.githubusercontent.com/sigoden/aichat/main/scripts/shell-integration/integration.zsh"
curl -s -L "${GHPROXY}${INTE_ZSH}" | sed 's#\\ee#^Y#' > ~/.zshrc.d/90aichat.zsh
