#!/bin/sh -v

sudo apt install docker.io docker-compose

sudo mkdir -p /etc/docker
sudo tee /etc/docker/daemon.json > /dev/null <<'EOF'
{
  "bip": "172.17.0.1/24",
  "default-address-pools": [
    {
      "base": "172.18.0.0/16",
      "size": 24
    }
  ]
}
EOF

# Add the docker group if it doesn't already exist.
sudo groupadd docker 2>/dev/null || true

# Add the connected user "${USER}" to the docker group.
# Change the user name to match your preferred user.
# You may have to logout and log back in again for
# this to take effect.
sudo gpasswd -a ${USER} docker

sudo systemctl enable docker

sudo systemctl restart docker


sudo docker pull busybox
sudo docker run -i -t busybox /bin/echo "hello, docker."
