#!/bin/sh -v

sudo apt install docker.io


# Add the docker group if it doesn't already exist.
sudo groupadd docker

# Add the connected user "${USER}" to the docker group.
# Change the user name to match your preferred user.
# You may have to logout and log back in again for
# this to take effect.
sudo gpasswd -a ${USER} docker

sudo systemctl enable docker

sudo systemctl restart docker


sudo docker pull busybox
sudo docker run -i -t busybox /bin/echo "hello, docker."
