#!/bin/sh -v

curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg
sudo install -o root -g root -m 644 microsoft.gpg /etc/apt/trusted.gpg.d/
sudo mv microsoft.gpg /etc/apt/trusted.gpg.d/microsoft.gpg
sudo sh -c 'echo "deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main" > /etc/apt/sources.list.d/vscode.list'

sudo apt update
sudo apt install apt-transport-https
sudo apt install code


code --install-extension MS-CEINTL.vscode-language-pack-zh-hans

#code --install-extension christian-kohler.path-intellisense
code --install-extension ionutvmi.path-autocomplete

code --install-extension vscodevim.vim

#code --install-extension ms-vscode.cpptools
