#!/bin/sh

sudo dpkg --add-architecture i386 && sudo apt update && sudo apt install wine32
sudo apt install winetricks
sudo apt install gnome-shell-extension-top-icons-plus


mkdir -p "$HOME/Wine/WeChat"

WINARCH=win32 LANG=zh_CN.UTF-8 WINEPREFIX=$HOME/Wine/WeChat winecfg
WINARCH=win32 LANG=zh_CN.UTF-8 WINEPREFIX=$HOME/Wine/WeChat winetricks # Install riched20.dll


#wget https://dldir1.qq.com/weixin/Windows/WeChatSetup.exe
WINARCH=win32 LANG=zh_CN.UTF-8 WINEPREFIX=$HOME/Wine/WeChat wine WeChatSetup.exe
WINARCH=win32 LANG=zh_CN.UTF-8 WINEPREFIX=$HOME/Wine/WeChat wine \
	"$HOME/Wine/WeChat/drive_c/Program Files\ (x86)/Tencent/WeChat/WeChat.exe"


rm -rf ~/.local/share/applications/wine/Programs/微信

cat > ~/.local/share/applications/wine/Programs/wechat.desktop << EOF
[Desktop Entry]
Name=WeChat
Exec=env WINARCH=win32 LANG=zh_CN.UTF-8 WINEPREFIX=$HOME/Wine/WeChat wine "$HOME/Wine/WeChat/drive_c/Program Files (x86)/Tencent/WeChat/WeChat.exe"
Type=Application
StartupNotify=true
Icon=06F2_WeChat.0
StartupWMClass=wechat.exe
EOF

#killall -HUP gnome-shell
