#!/bin/sh -v

WPSDEB=`curl https:/linux.wps.cn/\# | grep amd64.deb | sed -e 's/^.*"https/https/' -e 's/amd64.deb".*$/amd64.deb/'`
wget -c -O /tmp/wps-office.deb "$WPSDEB"
sudo dpkg -i /tmp/wps-office.deb
#rm /tmp/wps-office.deb
