#!/bin/sh -v

WPSDEB="http://kdl.cc.ksosoft.com/wps-community/download/6757/wps-office_10.1.0.6757_amd64.deb"
wget -c -O /tmp/wps-office_10.1.0.6757_amd64.deb "$WPSDEB"
sudo dpkg -i /tmp/wps-office_10.1.0.6757_amd64.deb
#rm /tmp/wps-office_10.1.0.6757_amd64.deb

git clone https://github.com/IamDH4/ttf-wps-fonts.git /tmp/ttf-wps-fonts
(cd /tmp/ttf-wps-fonts && sudo ./install.sh)
#rm -rf /tmp/ttf-wps-fonts

FONTSDEB="http://kdl.cc.ksosoft.com/wps-community/download/fonts/wps-office-fonts_1.0_all.deb"
wget -c -O /tmp/wps-office-fonts_1.0_all.deb "$FONTSDEB"
sudo dpkg -i /tmp/wps-office-fonts_1.0_all.deb
#rm /tmp/wps-office-fonts_1.0_all.deb
