#!/bin/sh -v

XMINDDEB="http://dl2.xmind.cn/XMind-ZEN-for-Linux-64bit.deb"
wget -c -O /tmp/XMind-ZEN-for-Linux-64bit.deb "$XMINDDEB"
sudo dpkg -i /tmp/XMind-ZEN-for-Linux-64bit.deb
sudo apt --fix-broken install
