#!/bin/sh -v

sudo apt install samba avahi-daemon
sudo systemctl enable smbd.service
sudo systemctl enable avahi-daemon.service

sudo smbpasswd -a "$USER"

sudo cp /etc/samba/smb.conf /etc/samba/smb.conf.default
cat << EOF | sudo tee /etc/samba/smb.conf
[global]
   workgroup = WORKGROUP
   log file = /var/log/samba/log.%m
   max log size = 1000
   logging = file
   panic action = /usr/share/samba/panic-action %d
   server role = standalone server
   obey pam restrictions = yes
   unix password sync = yes
   passwd program = /usr/bin/passwd %u
   passwd chat = *Enter\snew\s*\spassword:* %n\n *Retype\snew\s*\spassword:* %n\n *password\supdated\ssuccessfully* .
   pam password change = yes
   socket options = IPTOS_LOWDELAY TCP_NODELAY

[TimeMachine]
   comment = Time Machine
   path = /home/%U/TimeMachine
   browseable = yes
   writeable = yes
   valid users = $USER
   inherit acls = yes
   spotlight = yes
   ea support = yes
   vfs objects = catia fruit streams_xattr
   fruit:aapl = yes
   fruit:model = MacPro
   fruit:time machine = yes
   durable handles = yes
   kernel oplocks = no
   kernel share modes = no
   posix locking = no
EOF

cat << EOF | sudo tee /etc/avahi/services/timemachine.service
<?xml version="1.0" standalone='no'?>
<!DOCTYPE service-group SYSTEM "avahi-service.dtd">
<service-group>
 <name replace-wildcards="yes">%h</name>
 <service>
   <type>_smb._tcp</type>
   <port>445</port>
 </service>
 <service>
   <type>_device-info._tcp</type>
   <port>0</port>
   <txt-record>model=RackMac</txt-record>
 </service>
 <service>
   <type>_adisk._tcp</type>
   <txt-record>sys=waMa=0,adVF=0x100</txt-record>
   <txt-record>dk0=adVN=TimeMachine,adVF=0x82</txt-record>
 </service>
</service-group>
EOF

mkdir -p ~/TimeMachine
cat > ~/TimeMachine/.com.apple.TimeMachine.quota.plist << EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>GlobalQuota</key>
    <integer>200000000000</integer>
  </dict>
</plist>
EOF

sudo systemctl restart smbd.service
sudo systemctl restart avahi-daemon.service
