#!/bin/sh -v

[ `which aptitude` ] && sudo aptitude install curl git

export NVM_DIR="$HOME/.nvm" && (
	git clone https://github.com/creationix/nvm.git "$NVM_DIR"
	cd "$NVM_DIR"
	git checkout `git describe --abbrev=0 --tags --match "v[0-9]*" origin`
)

mkdir -p ~/.bashrc.d
cat > ~/.bashrc.d/nvm.bash << EOF
# Activate nvm
export NVM_DIR="\$HOME/.nvm"
[ -s "\$NVM_DIR/nvm.sh" ] && . "\$NVM_DIR/nvm.sh" # This loads nvm
[[ -r \$NVM_DIR/bash_completion ]] && . \$NVM_DIR/bash_completion
EOF
