#!/bin/bash

run() {
	echo $@
	eval $@
}

source $HOME/.nvm/nvm.sh

[ $(which aptitude) ] && run sudo aptitude install build-essential libssl-dev

run nvm install --lts
run nvm alias default lts/*
run use default
run npm install -g yarn
run yarn config set registry https://registry.npm.taobao.org
