#!/bin/bash

run() {
	echo $@
	eval $@
}

(
	cd "$NVM_DIR"
	git fetch origin
	git checkout `git describe --abbrev=0 --tags --match "v[0-9]*" origin`
) && . "$NVM_DIR/nvm.sh"

run nvm install --lts
run nvm alias default lts/*
run nvm use default
run npm install -g yarn
