#!/bin/sh


git clone https://github.com/yyuu/pyenv.git ~/.pyenv
git clone https://github.com/yyuu/pyenv-virtualenv.git \
	~/.pyenv/plugins/pyenv-virtualenv
git clone https://github.com/yyuu/pyenv-pip-rehash.git \
	~/.pyenv/plugins/pyenv-pip-rehash
git clone git://github.com/yyuu/pyenv-update.git \
	~/.pyenv/plugins/pyenv-update


cat >> $HOME/.bashrc << EOF

# Define environment variable for pyenv
export PYENV_ROOT="\$HOME/.pyenv"
export PATH="\$PYENV_ROOT/bin:\$PATH"
export PYENV_VIRTUALENV_DISABLE_PROMPT=1
# Add pyenv init to your shell
eval "\$(pyenv init -)"
eval "\$(pyenv virtualenv-init -)"
# For Pyenv/Homebrew Combination
# https://github.com/yyuu/pyenv/issues/106
alias brew="env PATH=\${PATH//\$(pyenv root)\/shims:/} brew"
EOF


echo "Restart your shell so that PATH changes take effect."
