#!/bin/bash

# Please see the pyenv wiki for solutions to common problems.
# https://github.com/yyuu/pyenv/wiki
# https://github.com/pyenv/pyenv/wiki/Common-build-problems

eval "$(pyenv init -)"

pyenv update

PY2_VERSION="$(pyenv install -l | grep '^ *2.' | grep -v dev | tail -1)"
pyenv install $PY2_VERSION

PY3_VERSION="$(pyenv install -l | grep '^ *3.' | grep -v dev | tail -1)"
pyenv install $PY3_VERSION

CONDA_VERSION="$(pyenv install -l | grep anaconda | tail -1)"
pyenv install $CONDA_VERSION

pyenv global $PY3_VERSION $PY2_VERSION
