#!/bin/bash

# Please see the pyenv wiki for solutions to common problems.
# https://github.com/yyuu/pyenv/wiki
# https://github.com/pyenv/pyenv/wiki/Common-build-problems

pyenv install 2.7.13

pyenv install 3.6.0

pyenv install anaconda3-5.1.0

pyenv global 3.6.0 2.7.13
