#!/bin/bash

PY_VERSION=3.6.0
VENV=flask

eval "$(pyenv init -)"

pyenv uninstall $VENV
pyenv virtualenv $PY_VERSION $VENV

pyenv shell $VENV
pip install --upgrade pip
pip install pipdeptree
pip install pylint yapf flask
pip install flask

python -m pipdeptree

#cd the_project_root
#pyenv local --unset
#pyenv local $VENV
