#!/bin/bash

eval "$(pyenv init -)"

PipInstall(){
	PY_VERSION=$1

	pyenv shell "${PY_VERSION}"
	pip install --upgrade pip
	pip install pipenv
	pip install pipdeptree
	python -m pipdeptree
	pyenv shell --unset
}

PY2_VERSION="$(pyenv global | grep '^2')"   
PipInstall $PY2_VERSION

PY3_VERSION="$(pyenv global | grep '^3')"   
PipInstall $PY3_VERSION

mkdir -p ~/.profile.d
cat > ~/.profile.d/pipenv.sh << EOF
eval "\$(pipenv --completion)"
EOF

