#!/bin/bash

eval "$(pyenv init -)"

VENV=django
PY_VERSION="$(pyenv global | grep '^3')"

pyenv uninstall $VENV
pyenv virtualenv "$PY_VERSION" "$VENV"

pyenv shell $VENV
pip install --upgrade pip
pip install pipenv
pip install pipdeptree
python -m pipdeptree

pip install django
python -m pipdeptree

#cd ~/tmp
#pyenv activate django
#django-admin startproject DjangoDemo
#cd DjangoDemo
#pyenv local --unset
#pyenv local $VENV
#python manage.py runserver
