#!/usr/bin/env zsh

mkdir -p ~/tmp/flask-demo
cd ~/tmp/flask-demo

pdm init -n
pdm use python3
pdm add  flask
#pdm add --dev pytest pylint yapf

cat > hello.py << EOF
from flask import Flask
app = Flask(__name__)

@app.route('/')
def hello_world():
    return 'Hello, World!'
EOF

export FLASK_APP=hello.py
export FLASK_ENV=development
pdm run flask run

#rm -rf ~/tmp/flask-demo
