#!/bin/bash

mkdir -p ~/tmp/flask-demo
cd ~/tmp/flask-demo

pipenv --python 3
pipenv install flask
#pipenv install --dev pytest pylint yapf

cat > hello.py << EOF
from flask import Flask
app = Flask(__name__)

@app.route('/')
def hello_world():
    return 'Hello, World!'
EOF

export FLASK_APP=hello.py
export FLASK_ENV=development
pipenv run flask run

#pipenv --rm
#rm -rf ~/tmp/flask-demo
