#!/usr/bin/env zsh

uv init ~/tmp/flask-demo
cd ~/tmp/flask-demo

uv add flask
#uv add --dev pytest pylint yapf

cat > hello.py << EOF
from flask import Flask

app = Flask(__name__)

@app.route('/')
def hello_world():
    return 'Hello, World!'

if __name__ == '__main__':
    app.run(debug=True)
EOF

export FLASK_APP=hello.py
export FLASK_ENV=development
uv run -- flask run

#rm -rf ~/tmp/flask-demo
