#!/usr/bin/env zsh

#apt install jupyter || brew install jupyter

mkdir -p ~/tmp/jupyter-demo
cd ~/tmp/jupyter-demo

pdm init -n
pdm add ipykernel
pdm run python3 -m ipykernel install --user --name "$(basename "$PWD")"

pdm add numpy pandas matplotlib

#jupyter kernelspec remove "$(basename "$PWD")"
#rm -rf ~/tmp/jupyter-demo
