#!/bin/sh -v

[ -f ~/.zshrc ] && cp ~/.zshrc ~/.zshrc.orig
cat > ~/.zshrc << EOF
# ~/.zshrc

if [ -f /etc/zshrc ]; then
    source /etc/zshrc
fi

PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

if [ "\`id -u\`" -eq 0 ]; then
    PATH="\$PATH:/root/bin"
else
    PATH="\$HOME/bin:\$PATH"
fi

if [ -d /opt/X11/bin ]; then
    PATH="\$PATH:/opt/X11/bin"
fi

# Ignore the permission issues and load the completion system normally.
ZSH_DISABLE_COMPFIX=true

if [ -d ~/.zshrc.d ]; then
    for i in ~/.zshrc.d/*.zsh; do
        if [ -r \$i ]; then
            source \$i
        fi
    done
    unset i
fi

if [ -d /etc/profile.d ]; then
    for i in /etc/profile.d/*.sh; do
        if [ -r \$i ]; then
            source \$i
        fi
    done
    unset i
fi

if [ -d ~/.profile.d ]; then
    for i in ~/.profile.d/*.sh; do
        if [ -r \$i ]; then
            source \$i
        fi
    done
    unset i
fi
EOF
