#!/bin/sh -v

rm -rf ~/.oh-my-zsh
git clone https://github.com/robbyrussell/oh-my-zsh.git ~/.oh-my-zsh
mkdir -p ~/.zshrc.d
cat > ~/.zshrc.d/10oh-my-zsh.zsh << EOF
export ZSH=~/.oh-my-zsh
ZSH_THEME="ys"
plugins=(git vi-mode)
plugins+=(ripgrep fzf)
#plugins+=(nvm pyenv rbenv)
plugins+=(asdf direnv)
plugins+=(node npm yarn)
plugins+=(python pip pipenv pdm)
plugins+=(ruby gem bundler)
plugins+=(docker docker-compose vagrant)

EOF

git clone https://github.com/zsh-users/zsh-completions \
	~/.oh-my-zsh/custom/plugins/zsh-completions
cat >> ~/.zshrc.d/10oh-my-zsh.zsh << EOF
# zsh-completions
plugins+=(zsh-completions)
# http://zsh.sourceforge.net/Doc/Release/Completion-System.html#Initialization
#autoload -U compinit && compinit -u
autoload -U compinit && compinit

EOF

git clone https://github.com/zsh-users/zsh-syntax-highlighting.git \
	~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting
cat >> ~/.zshrc.d/10oh-my-zsh.zsh << EOF
# Zsh Syntax Highlighting
plugins+=(zsh-syntax-highlighting)

EOF

git clone https://github.com/Aloxaf/fzf-tab.git \
	~/.oh-my-zsh/custom/plugins/fzf-tab
cat >> ~/.zshrc.d/10oh-my-zsh.zsh << EOF
# fzf-tab
plugins+=(fzf-tab)

EOF

git clone https://github.com/zsh-users/zsh-autosuggestions \
	~/.oh-my-zsh/custom/plugins/zsh-autosuggestions
cat >> ~/.zshrc.d/10oh-my-zsh.zsh << EOF
# zsh-autosuggestions
plugins+=(zsh-autosuggestions)

EOF

cat >> ~/.zshrc.d/10oh-my-zsh.zsh << EOF
source \$ZSH/oh-my-zsh.sh
EOF
