#!/bin/sh -v

rm -rf ~/.oh-my-zsh
git clone git://github.com/robbyrussell/oh-my-zsh.git ~/.oh-my-zsh
mkdir -p ~/.zshrc.d
cat > ~/.zshrc.d/oh-my-zsh.zsh << EOF
export ZSH=~/.oh-my-zsh
ZSH_THEME="ys"
plugins=(command-not-found git vi-mode)
plugins+=(ripgrep fzf zsh-interactive-cd)
plugins+=(nvm node npm yarn)
plugins+=(pyenv python pip)
plugins+=(rbenv ruby gem bundler)
plugins+=(docker docker-compose vagrant)

EOF

git clone git://github.com/zsh-users/zsh-autosuggestions \
	~/.oh-my-zsh/custom/plugins/zsh-autosuggestions
cat >> ~/.zshrc.d/oh-my-zsh.zsh << EOF
# zsh-autosuggestions
plugins+=(zsh-autosuggestions)

EOF
cat > ~/.zshrc.d/zsh-autosuggestions.zsh<< EOF
bindkey '^ ' autosuggest-accept
EOF
test "$(uname)" = "Linux" &&
    cat > ~/.oh-my-zsh/custom/zsh-autosuggestions-config.zsh << EOF
# https://github.com/Microsoft/console/pull/181
#ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=10'

EOF

git clone git://github.com/zsh-users/zsh-completions \
	~/.oh-my-zsh/custom/plugins/zsh-completions
cat >> ~/.zshrc.d/oh-my-zsh.zsh << EOF
# zsh-completions
plugins+=(zsh-completions)
# http://zsh.sourceforge.net/Doc/Release/Completion-System.html#Initialization
#autoload -U compinit && compinit -u
autoload -U compinit && compinit

EOF

git clone git://github.com/zsh-users/zsh-syntax-highlighting.git \
	~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting
cat >> ~/.zshrc.d/oh-my-zsh.zsh << EOF
# zsh-syntax-highlighting
plugins+=(zsh-syntax-highlighting history-substring-search)

EOF

cat >> ~/.zshrc.d/oh-my-zsh.zsh << EOF
source \$ZSH/oh-my-zsh.sh
EOF
