#!/bin/sh -v

cat > ~/.zshrc.d/20fzf-tab.zsh << 'EOF'
# Disable sort when completing `git checkout`
zstyle ':completion:*:git-checkout:*' sort false

# Set list-colors to enable filename colorizing
zstyle ':completion:*' list-colors ${(s.:.)LS_COLORS}

# Disable sort when completing options of any command
zstyle ':completion:complete:*:options' sort false

# Use input as query string when completing zlua
zstyle ':fzf-tab:complete:_zlua:*' query-string input

# Show file contents
zstyle ':fzf-tab:complete:*:*' fzf-preview 'fzf-previewer ${(Q)realpath}'
zstyle ':fzf-tab:*' fzf-min-height 12

# Show environment variables
zstyle ':fzf-tab:complete:((-parameter-|unset):|(export|typeset|declare|local):argument-rest)'\
    fzf-preview 'echo ${(P)word}'

# Disable previews for commands options and arguments
zstyle ':fzf-tab:complete:-command-:*' fzf-preview
zstyle ':fzf-tab:complete:*:options' fzf-preview
zstyle ':fzf-tab:complete:*:argument-1' fzf-preview

# Display colors for different groups and their descriptions
zstyle ':completion:*:descriptions' format '[%d]'
EOF
