#!/usr/bin/env -S zsh -v

cat > ~/.zshrc.d/30pdm.zsh<< 'EOF'
eval "$(pdm --pep582 zsh)"
EOF

eval "$(pdm --pep582 zsh)"

ZSH_CUSTOM=~/.oh-my-zsh/custom

mkdir -p $ZSH_CUSTOM/plugins/pdm
pdm completion zsh > $ZSH_CUSTOM/plugins/pdm/_pdm
