#!/bin/sh -v

UPDATER=~/.oh-my-zsh/tools/upgrade.sh

cp $UPDATER $UPDATER.orig
sed "s/exit \$status/#exit \$status/" $UPDATER.orig > $UPDATER

cat >> $UPDATER << EOF

# Update custom plugins and themes
printf "\n\${BLUE}%s\${RESET}\n" "Updating custom plugins and themes"
cd custom/
for plugin in plugins/*/ themes/*/; do
  if [ -d "\$plugin/.git" ]; then
     printf "\${YELLOW}%s\${RESET}\n" "\${plugin%/}"
     git -C "\$plugin" pull
  fi
done

# Exit with \`1\` if the update failed
exit \$status
EOF
