#!/bin/sh -v

UPDATER=~/.oh-my-zsh/tools/upgrade.sh

git -C ~/.oh-my-zsh/ reset --hard origin/master

cp -f $UPDATER $UPDATER.tmp
sed "s/exit \$ret/#exit \$ret/" $UPDATER.tmp > $UPDATER
rm $UPDATER.tmp

cat >> $UPDATER << 'EOF'

# Update custom plugins
printf "\n${BLUE}%s${RESET}\n" "Updating custom plugins"
cd custom/plugins

for plugin in */; do
  if [ -d "$plugin/.git" ]; then
     printf "${YELLOW}%s${RESET}\n" "${plugin%/}"
     git -C "$plugin" pull
  fi
done

# Exit with \`1\` if the update failed
exit $ret
EOF
