#!/bin/sh -v

aptitude -y install ruby-full

#aptitude -y install rubygems
VERSION=1.8.12
GEMS=http://production.cf.rubygems.org/rubygems/rubygems-$VERSION.tgz
rm -rf /usr/local/src/rubygems-$VERSION
wget -O - $GEMS | tar zxv -C /usr/local/src
PWD_TMP=$PWD
cd /usr/local/src/rubygems-$VERSION
ruby setup.rb
cd $PWD_TMP
ln -f -s /usr/bin/gem1.8 /usr/local/bin/gem 

gem install bundler

#gem install ruby-debug

#gem install snmp

aptitude -y install imagemagick
aptitude -y install libmagick9-dev
#gem install rmagick

aptitude -y install sqlite3
aptitude -y install libsqlite3-dev
#gem install sqlite3

#aptitude -y install mysql-client
#aptitude -y install libmysqlclient-dev
#gem install mysql2

#gem install rails

#gem install termios
#gem install capistrano
