#!/bin/sh -v

if [ ! -f /etc/apt/sources.list.default ]; then
	cp /etc/apt/sources.list /etc/apt/sources.list.default
fi
cat > /etc/apt/sources.list.archive << EOF
deb http://archive.ubuntu.com/ubuntu/ precise main restricted universe multiverse
deb http://archive.ubuntu.com/ubuntu/ precise-updates main restricted universe multiverse
deb http://archive.ubuntu.com/ubuntu/ precise-security main restricted universe multiverse
#deb http://archive.ubuntu.com/ubuntu/ precise-backports main restricted universe multiverse
#deb http://archive.ubuntu.com/ubuntu/ precise-proposed main restricted universe multiverse
deb http://archive.canonical.com/ubuntu precise partner
deb http://extras.ubuntu.com/ubuntu precise main
EOF
cp /etc/apt/sources.list.archive /etc/apt/sources.list
apt-get update
apt-get install aptitude
aptitude -y update
aptitude -y full-upgrade

aptitude -y install bash bash-completion
grep "set -o vi" /etc/bash.bashrc > /dev/null || cat >> /etc/bash.bashrc << EOF

# Use a vi-style command line editing interface
set -o vi
EOF

aptitude -y install ssh
