#!/bin/sh -v

aptitude -y install screen

aptitude -y install rsync

aptitude -y install unison

aptitude -y install convmv

aptitude -y install tofrodos

aptitude -y install unrar

aptitude -y install p7zip

aptitude -y install curl

aptitude -y install wget

aptitude -y install lftp

aptitude -y install stunnel

aptitude -y install proxychains
if [ ! -f /etc/proxychains.conf.default ]; then
	cp /etc/proxychains.conf /etc/proxychains.conf.default
fi
cp /etc/proxychains.conf /etc/proxychains.conf.orig
if grep '^socks4' /etc/proxychains.conf >/dev/null; then
	sed 's/^socks4/#socks4/' /etc/proxychains.conf.default > /etc/proxychains.conf
	echo "socks5 127.0.0.1 7070" >> /etc/proxychains.conf
fi
