#!/bin/sh -v

apt-key adv --keyserver keyserver.ubuntu.com --recv 7F0CEB10

cat > /etc/apt/sources.list.d/mongodb.list << EOF
deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen
EOF

aptitude -y update
aptitude -y install mongodb-10gen

#update-rc.d -f mongodb remove
