#!/bin/sh -v

cat > /etc/udev/rules.d/51-android.rules << EOF
# adb protocol on maguro/toro (Galaxy Nexus)
SUBSYSTEM=="usb", ATTR{idVendor}=="04e8", ATTR{idProduct}=="6860", MODE="0600", GROUP="plugdev"
# fastboot protocol on maguro/toro (Galaxy Nexus)
SUBSYSTEM=="usb", ATTR{idVendor}=="18d1", ATTR{idProduct}=="4e30", MODE="0600", GROUP="plugdev"
EOF

chmod a+r /etc/udev/rules.d/51-android.rules

service udev restart
