#!/bin/sh -v

VENDOR="Samsung Electronics Co., Ltd"
ID_VENDOR=`lsusb |grep "$VENDOR" | sed -e 's/.*ID //' -e 's/:.*$//'`
ID_PRODUCT=`lsusb |grep "$VENDOR" | sed -e 's/.*://' -e 's/ .*$//'`

cat > /etc/udev/rules.d/51-android.rules << EOF
SUBSYSTEM=="usb", ATTR{idVendor}=="$ID_VENDOR", ATTR{idProduct}=="$ID_PRODUCT", MODE="0666", GROUP="plugdev"
EOF

cat >> /etc/udev/rules.d/51-android.rules << EOF

# adb protocol on maguro/toro (Galaxy Nexus)
SUBSYSTEM=="usb", ATTR{idVendor}=="04e8", ATTR{idProduct}=="6860", MODE="0666", GROUP="plugdev"
# fastboot protocol on maguro/toro (Galaxy Nexus)
SUBSYSTEM=="usb", ATTR{idVendor}=="18d1", ATTR{idProduct}=="4e30", MODE="0666", GROUP="plugdev"
EOF

chmod a+r /etc/udev/rules.d/51-android.rules

service udev restart
