#!/bin/sh -v

rm -f ~/bin
ln -f -s usr/bin ~/bin

grep "# set RUBYLIB" ~/.profile || cat >> ~/.profile << EOF

# set RUBYLIB
RUBYLIB=\$HOME/.ruby
export RUBYLIB
EOF

cat > ~/.irbrc << EOF
IRB.conf[:AUTO_INDENT] = true
IRB.conf[:USE_READLINE] = true
IRB.conf[:LOAD_MODULES] ||= []
IRB.conf[:LOAD_MODULES] |= ['irb/completion']
EOF

mkdir -p ~/.lftp
cat > ~/.lftp/rc << EOF
set ftp:charset "GB18030"
EOF

gconftool --type boolean -s /desktop/ibus/panel/show_icon_on_systray true
gconftool --type boolean -s /desktop/ibus/panel/show true
gsettings set com.canonical.Unity.Panel systray-whitelist "['all']"

#mkdir -p ~/.config/autostart
#cat > ~/.config/autostart/restart-ibus.desktop << EOF
#[Desktop Entry]
#Type=Application
#Exec=ibus-daemon --daemonize --xim --replace
#Hidden=false
#NoDisplay=false
#X-GNOME-Autostart-enabled=true
#Name[zh_CN]=restart ibus
#Name=restart ibus
#Comment[zh_CN]=Restart ibus-daemon
#Comment=Restart ibus-daemon
#EOF
