#!/bin/sh -v

aptitude -y install traceroute

aptitude -y install tcptraceroute

aptitude -y install netcat

aptitude -y install snmp

aptitude -y install hping3

aptitude -y install nmap

aptitude -y install tcpdump

aptitude -y install wireshark

aptitude -y install minicom lrzsz
cat > /etc/minicom/minirc.9600 << EOF
pu port             /dev/ttyS0
pu baudrate         9600
pu bits             8
pu parity           N
pu stopbits         1
pu minit
pu mreset
pu rtscts           No
EOF
ln -f -s minirc.9600 /etc/minicom/minirc.dfl

aptitude -y install tftp-hpa tftpd-hpa
if [ ! -f /etc/default/tftpd-hpa.default ]; then
	cp /etc/default/tftpd-hpa /etc/default/tftpd-hpa.default
fi
grep "\-\-create" /etc/default/tftpd-hpa || cat >> /etc/default/tftpd-hpa << EOF
TFTP_OPTIONS="--create --secure"
EOF
if [ ! -f /etc/init/tftpd-hpa.conf.default ]; then
	cp /etc/init/tftpd-hpa.conf /etc/init/tftpd-hpa.conf.default
fi
sed 's/--address \${TFTP_ADDRESS} //' /etc/init/tftpd-hpa.conf.default > /etc/init/tftpd-hpa.conf
chown tftp:tftp /var/lib/tftpboot
rm -f /srv/tftp
ln -f -s /var/lib/tftpboot /srv/tftp
service tftpd-hpa restart
#update-rc.d -f tftpd-hap remove
